name: Deploy Flutter Web

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'   # ← Versiyonu manuel yazma, stable her zaman çalışır

      - run: flutter config --enable-web

      - run: flutter pub get

      - run: flutter build web --release --base-href "/redbook/"

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
